### ISSUE TITLE
Github install script went rogue in WSL2

### ISSUE THREAD

**Issue by takase1121** [franko/lhelper#2]
The github-install script enumerate PATH to get a path with `/bin`. Coincidentally, the first path in my PC that have `/bin` is on Windows. lhelper is installed there and that causes big slowdowns.

**Comment by franko** [comment]
Thank you for reporting the issue. I wanted the installer to be smart and figure out the PATH to install but really, I think it is a bad idea. I think I will remove it. Instead the simple "install" script should be used:

```
bash install <prefix-dir>
```

where the install prefix is explicitly provided.

**Comment by takase1121** [comment]
I think a better option is to prompt the installation location (I think that's the intention of the install_github script, its for people to `curl | bash`).

**Comment by franko** [comment]
Done in the master branch!

The script now asks for the prefix directory to install. I took also the opportunity to polish also a few things about the installer.

Feel free to close the issue if you think now is fine. I made some tests locally and everything works correctly.
