### ISSUE TITLE
Will it work on Cygwin?

### ISSUE THREAD

**Issue by ghost** [franko/lhelper#4]
You only mentioned MSYS2 but not Cygwin.

**Comment by franko** [comment]
I never attempted to use lhelper with cygwin but it may work provided some commands like meson, gnu make, cmake etc are available.

**Comment by ghost** [comment]
> I never attempted to use lhelper with cygwin but it may work provided some commands like meson, gnu make, cmake etc are available.

First you have to add $OSTYPE cygwin to your install script and install-github script

**Comment by franko** [comment]
Thank you I will fix for the cygwin environment.
