### ISSUE TITLE
MSYS2

### ISSUE THREAD

**Issue by ghost** [franko/lhelper#5]
MSYS2 has many sub systems: MINGW32, MINGW64, UCRT64, CLANG64, MSYS,... When you mentioned MSYS2 on README.md, I think you mean the MSVCRT based MINGW32 and MINGW64? Will it work on UCRT64 or CLANG64 too? The last sub system, MSYS, is indeed MSYS2's fork of Cygwin (it links with msys-2.0.dll, not cygwin-1.dll). It behaved exactly like Cygwin, except sometimes build scripts doesn't correctly detect it and failed to work correctly because it uses the different triplet than Cygwin.

**Comment by franko** [comment]
I will may be clarify the README. Lhelper requires MSYS2 to work but it can generate libraries for any subsystem: MINGW64, CLANG64 or any of them. One just needs to instruct lhelper to use the corresponding compiler.

For example I routinely compile my applications using the MINGW64 subsystem and lhelper to create binaries that don't depend on the msys dlls.
