### ISSUE TITLE
Fix cp: cannot create regular file : No such file or directory

### ISSUE THREAD

**Issue by ghost** [franko/lhelper#6]
The reason is on your install script you tell cp to copy to "$DESTDIR/bin" without checking if "$DESTDIR/bin" exists or not. Most of the time, the directory $1 doesn't exist yet so you have to use mkdir -p to make sure it's exist.

You did mkdir -p "$DESTDIR/bin" but it's after the code for cp lh-$modname "$DESTDIR/bin" is executed and you have no mkdir -p "$DESTDIR" at all. I moved mkdir -p "$DESTDIR/bin" and make a mkdir -p "$DESTDIR". It worked without problems now:

PREFIX="$1"

if [ -z "${DESTDIR+x}" ]; then
    DESTDIR="$PREFIX"
    mkdir -p "$DESTDIR"
    mkdir -p "$DESTDIR/bin"
fi

**Comment by ghost** [comment]
This is about your install script, I didn't check your install-github script but you should review that script and fix if there is the same bug too.

**Comment by franko** [comment]
Thank you, I will fix this problem.
