### ISSUE TITLE
Allow using of nano to edit spec file

### ISSUE THREAD

**Issue by ghost** [franko/lhelper#7]
Currently it's hardcoded to use vim:

.local/bin/lhelper: line 1300: vim: command not found

The situation on most Linux distro and MSYS2 is they shipped with nano by default but not vim. IMO, the users should be able to use their favorite editor. Ask the users to set the environment variable EDITOR and lhelper will just use $EDITOR, otherwise fall back to vim.

**Comment by franko** [comment]
I have changed the behavior to try other editor before vim and print a message is the variable EDITOR is not set.

Thank you for pointing out this problem.
