### ISSUE TITLE
It's only about libraries?

### ISSUE THREAD

**Issue by ghost** [franko/lhelper#8]
I should pay a little more attention to it. The name of it is "Little Library Helper". I wanted to compile normal packages (including binaries), not just libraries. I tried to setup an environment to compile Lua and it successfully compiled Lua, but it's not the Lua interpreter I expected but just the Lua library liblua.a put on the directory with the same name as the environment name under .lhelper directory.

Perhaps winlibs is what I want. Too bad the author stated he will only support MSYS2. lhelper worked fine on Cygwin but is not what I want.

**Comment by franko** [comment]
It can build also the Lua command application, just pass the -app option with the Lua package in the lhelper script. By choice, without options lhelper will install only the library.

Your feedback is welcome, please remember that lhelper is a new project used only by myself currently.
